name: Run tests and linters
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [ 1.18 ]
    name: Tests Go ${{ matrix.go }}
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
